services:
  dev-ui:
    build:
      context: app
      target: dev
    volumes:
      - ui-node-modules:/opt/botbuilder/app/node_modules
      - ./app:/opt/botbuilder/app
  dev-server:
    build:
      context: server
      target: dev
    env_file:
      - .env
    volumes:
      - server-node-modules:/opt/botbuilder/server/node_modules
      - ./server:/opt/botbuilder/server
      - ./app/build:/opt/botbuilder/server/public
      - ./assets:/opt/botbuilder/assets
    ports:
      - "3000:3000"
  prod-ui:
    build:
      context: app
      target: prod
    volumes:
      - ./app:/opt/botbuilder/app
      - ./server/public:/opt/botbuilder/app/build
  prod-server:
    build:
      context: server
      target: prod
volumes:
  ui-node-modules:
  server-node-modules:
