name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: npm run build
      - name: Publish Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: npm run publish
  deploy:
    runs-on: ubuntu-latest
    needs: [ docker-image ]
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh workflow run cd.yml -R zachanator070/thezachcave.com.conf